### ISSUE TITLE
Syntax error in policy.py

### ISSUE THREAD

**Issue by hassaanhashmi** [openai/multiagent-competition#2]
I am facing a syntax error in line 75 of policy.py. The error prompt is pointing out that there is something wrong with using * as `def __init__`'s 3rd argument. Any help in this regard would be awesome. Thanks for reading through.

**Comment by MHHashmi** [comment]
Just solved it by deleting the argument "*" and rewriting python to python3 in demo_tasks.sh. Thanks anyways.

**Comment by ashwanirathee** [comment]
Hey @hassaanhashmi ,how did you resolve this issue??
